buildConfiguration:
  buildCommand: npx pages build
  installDependenciesStep:
    command: npm install
    requiredFiles:
      - package.json
      - package-lock.json
      - .npmrc
sitemap:
  disableSitemapGeneration: false
  fileName: expert-profile-sitemap
serving:
  reverseProxyPrefix: https://pros.turbotax.intuit.com/
staticRouting:
  - from: "/"
    to: https://pros-turbotax.app.intuit.com/pro-matching-intro
    statusCode: 301
  - from: ""
    to: https://pros-turbotax.app.intuit.com/pro-matching-intro
    statusCode: 301
  - from: "/index.html"
    to: https://pros-turbotax.app.intuit.com/pro-matching-intro
    statusCode: 301
