const directoryProfileFields: string[] = [
  "id",
  "uid",
  "name",
  "slug",
  "c_meta",
  "c_heroTitle",
  "c_heroDescription",
  "c_findAVerifiedPro",
  "c_findAVerifiedProHeroText",
  "c_directoryHeroImage",
  "c_onrampCTAURL",
  "dm_directoryChildren.slug",
  "dm_directoryChildren.name",
  "dm_directoryParents_directory.slug",
  "dm_directoryParents_directory.name",
  "dm_directoryChildren.dm_baseEntityCount",
  "dm_directoryChildren.dm_directoryChildren.slug",
  "dm_directoryChildren.dm_directoryChildren.dm_directoryChildren.slug",
  "dm_directoryChildren.dm_directoryChildren.dm_directoryChildren.dm_directoryChildren.slug",
];

const taxProsMainFields: string[] = [
  "id",
  "uid",
  "name",
  "slug",
  "c_meta",
  "c_heroTitle",
  "c_heroDescription",
  "c_findAVerifiedPro",
  "c_findAVerifiedProHeroText",
  "c_directoryHeroImage",
  "c_onrampCTAURL",
  "dm_directoryChildren.slug",
  "dm_directoryChildren.name",
  "dm_directoryChildren.address",
  "dm_directoryChildren.headshot",
  "dm_directoryChildren.mainPhone",
  "dm_directoryChildren.c_taxProName",
  "dm_directoryParents_directory.slug",
  "dm_directoryParents_directory.name",
  "dm_directoryChildren.googlePlaceId",
  "dm_directoryChildren.c_tagline",
  "dm_directoryChildren.dm_baseEntityCount",
  "dm_directoryChildren.dm_directoryChildren.slug",
  "dm_directoryChildren.dm_directoryChildren.dm_directoryChildren.slug",
  "dm_directoryChildren.dm_directoryChildren.dm_directoryChildren.dm_directoryChildren.slug",
];

export { directoryProfileFields, taxProsMainFields };
